baseURL = "https://docs.insigh.io"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "insigh.io documentation"
theme = ["hugo-video", "hugo-theme-learn"]
themesdir = "themes"
metaDataFormat = "yaml"

googleAnalytics = "G-6C5XMEGR8C"
# defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/insighio/docs/edit/master/content/"
  description = "insigh.io documentation"
  author = "insigh.io robot"
  disableBreadcrumb = false
  disableLanguageSwitchingButton = true
  disableNextPrev = false
  showVisitedLinks = false
  themeVariant = "mine"
  disableLandingPageButton = true
  
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  title = "insigh.io documentation"
  weight = 1
  languageName = "English"

[[menu.shortcuts]]
  name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
  identifier = "ds"
  url = "https://github.com/insighio"
  weight = 10

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-chart-line'></i> Platform"
  url = "https://console.insigh.io"
  weight = 11

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-microchip'></i> Hardware info"
  url = "https://insigh.io/iot-nodes/"
  weight = 12

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-blog'></i> insigh.io blog"
  identifier = "insighio-blog"
  url = "https://insigh.io/blog/"
  weight = 20

[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-users'></i> About us"
  url = "https://insigh.io/about-us/"
  weight = 30
