baseURL = "http://docs.insigh.io"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "insigh.io documentation"
theme = ["hugo-video", "hugo-theme-learn"]
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/insighio/docs/edit/master/content/"
  description = "insigh.io documentation"
  author = "insigh.io robot"
  disableBreadcrumb = false
  disableLanguageSwitchingButton = true
  disableNextPrev = false
  showVisitedLinks = false
  themeVariant = "mine"
  disableLandingPageButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "insigh.io documentation"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/insighio"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-microchip'></i> Hardware info"
url = "https://insigh.io/iot-nodes/"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-chart-line'></i> Platform info"
url = "https://insigh.io/iot-platform/"
weight = 11

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-blog'></i> insigh.io blog"
identifier = "insighio-blog"
url = "https://insigh.io/blog/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-users'></i> About us"
url = "https://insigh.io/about-us/"
weight = 30

# [Languages.fr]
# title = "Documentation du thème Hugo Learn"
# weight = 2
# languageName = "Français"

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
# url = "/showcase"
# weight = 11

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.fr.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
# url = "/credits"
# weight = 30

# [Languages.zh]
# title = "Hugo 主题的 Learn 文档"
# weight = 3
# languageName = "简体中文"

# [[Languages.zh.menu.shortcuts]]
# name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
# identifier = "ds"
# url = "https://github.com/matcornic/hugo-theme-learn"
# weight = 10

# [[Languages.zh.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> 展示区"
# url = "/showcase"
# weight = 11

# [[Languages.zh.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 文档"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.zh.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
# url = "/credits"
# weight = 30

[menu]

[[menu.main]]
    name = "Getting Started"
    url = "/gettingstarted/"
    identifier = "gettingstarted"
    weight = 10

[[menu.main]]
  name = "Create Account"
  url = "/gettingstarted/registeraccount/"
  identifier = "gettingstarted@registeraccount"
  parent="gettingstarted"
  weight = 10

[[menu.main]]
  name = "Create Device"
  url = "/gettingstarted/provisiondevice/"
  identifier = "gettingstarted@provisiondevice"
  parent="gettingstarted"
  weight = 20

[[menu.main]]
  name = "Configure Device"
  url = "/gettingstarted/configuration/"
  identifier = "gettingstarted@configuration"
  parent="gettingstarted"
  weight = 30

[[menu.main]]
  name = "Validation"
  url = "/gettingstarted/validation/"
  identifier = "gettingstarted@validation"
  parent="gettingstarted"
  weight = 40

[[menu.main]]
  name = "WiFi"
  url = "/gettingstarted/configuration/wifi/"
  identifier = "gettingstarted@configuration@wifi"
  parent="gettingstarted@configuration"
  weight = 10

[[menu.main]]
  name = "NBIoT"
  url = "/gettingstarted/configuration/nbiot/"
  identifier = "gettingstarted@configuration@nbiot"
  parent="gettingstarted@configuration"
  weight = 20

[[menu.main]]
  name = "LoRa"
  url = "/gettingstarted/configuration/lora/"
  identifier = "gettingstarted@configuration@lora"
  parent="gettingstarted@configuration"
  weight = 30

[[menu.main]]
  name = "Measurements"
  url = "/gettingstarted/configuration/measurements/"
  identifier = "gettingstarted@configuration@measurements"
  parent="gettingstarted@configuration"
  weight = 40

###############
[[menu.main]]
    name = "Hardware"
    url = "/hardware/"
    identifier = "hardware"
    weight = 20

###############
[[menu.main]]
    name = "Firmware API"
    url = "/firmwareapi/"
    identifier = "firmwareapi"
    weight = 30

[[menu.main]]
  name = "API"
  url = "/firmwareapi/api/"
  identifier = "firmwareapi@api"
  parent="firmwareapi"
  weight = 10

[[menu.main]]
  name = "device_info"
  url = "/firmwareapi/api/device_info/"
  identifier = "firmwareapi@api@device_info"
  parent="firmwareapi@api"
  weight = 10

[[menu.main]]
  name = "external"
  url = "/firmwareapi/api/external/"
  identifier = "firmwareapi@api@external"
  parent="firmwareapi@api"
  weight = 20

[[menu.main]]
  name = "gpio_handler"
  url = "/firmwareapi/api/gpio_handler/"
  identifier = "firmwareapi@api@gpio_handler"
  parent="firmwareapi@api"
  weight = 30

[[menu.main]]
  name = "logging"
  url = "/firmwareapi/api/logging/"
  identifier = "firmwareapi@api@logging"
  parent="firmwareapi@api"
  weight = 40

[[menu.main]]
  name = "utils"
  url = "/firmwareapi/api/utils/"
  identifier = "firmwareapi@api@utils"
  parent="firmwareapi@api"
  weight = 50

[[menu.main]]
  name = "networking"
  url = "/firmwareapi/api/networking/"
  identifier = "firmwareapi@api@networking"
  parent="firmwareapi@api"
  weight = 60

[[menu.main]]
  name = "wifi"
  url = "/firmwareapi/api/networking/wifi/"
  identifier = "firmwareapi@api@networking@wifi"
  parent="firmwareapi@api@networking"
  weight = 10

[[menu.main]]
  name = "nbiot"
  url = "/firmwareapi/api/networking/nbiot/"
  identifier = "firmwareapi@api@networking@nbiot"
  parent="firmwareapi@api@networking"
  weight = 20

[[menu.main]]
  name = "lora"
  url = "/firmwareapi/api/networking/lora/"
  identifier = "firmwareapi@api@networking@lora"
  parent="firmwareapi@api@networking"
  weight = 30

[[menu.main]]
  name = "protocols"
  url = "/firmwareapi/api/protocols/"
  identifier = "firmwareapi@api@protocols"
  parent="firmwareapi@api"
  weight = 70

[[menu.main]]
  name = "coap"
  url = "/firmwareapi/api/protocols/coap/"
  identifier = "firmwareapi@api@protocols@coap"
  parent="firmwareapi@api@protocols"
  weight = 10

[[menu.main]]
  name = "coap"
  url = "/firmwareapi/api/protocols/mqtt/"
  identifier = "firmwareapi@api@protocols@mqtt"
  parent="firmwareapi@api@protocols"
  weight = 20

[[menu.main]]
  name = "udp"
  url = "/firmwareapi/api/protocols/udp/"
  identifier = "firmwareapi@api@protocols@udp"
  parent="firmwareapi@api@protocols"
  weight = 30

[[menu.main]]
  name = "sensors"
  url = "/firmwareapi/api/sensors/"
  identifier = "firmwareapi@api@sensors"
  parent="firmwareapi@api"
  weight = 80

[[menu.main]]
  name = "analog"
  url = "/firmwareapi/api/sensors/analog/"
  identifier = "firmwareapi@api@sensors@analog"
  parent="firmwareapi@api@sensors"
  weight = 10

[[menu.main]]
  name = "bme680"
  url = "/firmwareapi/api/sensors/bme680/"
  identifier = "firmwareapi@api@sensors@bme680"
  parent="firmwareapi@api@sensors"
  weight = 20

[[menu.main]]
  name = "dht"
  url = "/firmwareapi/api/sensors/dht/"
  identifier = "firmwareapi@api@sensors@dht"
  parent="firmwareapi@api@sensors"
  weight = 30

[[menu.main]]
  name = "gl55"
  url = "/firmwareapi/api/sensors/gl55/"
  identifier = "firmwareapi@api@sensors@gl55"
  parent="firmwareapi@api@sensors"
  weight = 40

[[menu.main]]
  name = "scd30"
  url = "/firmwareapi/api/sensors/scd30/"
  identifier = "firmwareapi@api@sensors@scd30"
  parent="firmwareapi@api@sensors"
  weight = 50

[[menu.main]]
  name = "si7021"
  url = "/firmwareapi/api/sensors/si7021/"
  identifier = "firmwareapi@api@sensors@si7021"
  parent="firmwareapi@api@sensors"
  weight = 60

[[menu.main]]
  name = "tsl2561"
  url = "/firmwareapi/api/sensors/tsl2561/"
  identifier = "firmwareapi@api@sensors@tsl2561"
  parent="firmwareapi@api@sensors"
  weight = 70

[[menu.main]]
  name = "protocol"
  url = "/firmwareapi/api/sensors/protocol/"
  identifier = "firmwareapi@api@sensors@protocol"
  parent="firmwareapi@api@sensors"
  weight = 80

[[menu.main]]
  name = "onewire"
  url = "/firmwareapi/api/sensors/protocol/onewire/"
  identifier = "firmwareapi@api@sensors@protocol@onewire"
  parent="firmwareapi@api@sensors@protocol"
  weight = 10

[[menu.main]]
  name = "LoRa"
  url = "/firmwareapi/lora/"
  identifier = "firmwareapi@lora"
  parent="firmwareapi"
  weight = 20

[[menu.main]]
  name = "Encoding Protocol"
  url = "/firmwareapi/lora/encodingprotocol/"
  identifier = "firmwareapi@lora@encodingprotocol"
  parent="firmwareapi@lora"
  weight = 10

[[menu.main]]
  name = "Decoder"
  url = "/firmwareapi/lora/decoder/"
  identifier = "firmwareapi@lora@decoder"
  parent="firmwareapi@lora"
  weight = 20

[[menu.main]]
  name = "Sample Config Files"
  url = "/firmwareapi/sampleconfigfiles/"
  identifier = "firmwareapi@sampleconfigfiles"
  parent="firmwareapi"
  weight = 30

[[menu.main]]
  name = "WiFi Config Files"
  url = "/firmwareapi/sampleconfigfiles/wifi"
  identifier = "firmwareapi@sampleconfigfiles@wifi"
  parent="firmwareapi@sampleconfigfiles"
  weight = 10

[[menu.main]]
  name = "NBIoT Config Files"
  url = "/firmwareapi/sampleconfigfiles/nbiot"
  identifier = "firmwareapi@sampleconfigfiles@nbiot"
  parent="firmwareapi@sampleconfigfiles"
  weight = 20

[[menu.main]]
  name = "LoRa Config Files"
  url = "/firmwareapi/sampleconfigfiles/lora"
  identifier = "firmwareapi@sampleconfigfiles@lora"
  parent="firmwareapi@sampleconfigfiles"
  weight = 30

###############
[[menu.main]]
    name = "Console"
    url = "/cloudplatform/"
    identifier = "cloudplatform"
    weight = 40